;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                                  DISPLAY.INC                               ;
;                              Display Definitions                           ;
;                                 Include File                               ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; This file contains the definitions for the display functions.
;
; Revision History:
;     10/27/15  Nancy Cao      initial revision
;     11/01/15  Nancy Cao      updated definitions and comments

; definitions
MAX_DIGIT       EQU     8              ; the max digits that can be displayed